server:
  shutdown: graceful
  port: 8080

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    #    database-platform: mysql
    hibernate:
      ddl-auto: none
  #    properties:
  #      hibernate:
  #        format_sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ddd-order?serverTimezone=UTC&characterEncoding=UTF-8
      username: user
      password: pass
  flyway:
    user: user
    password: pass
    schemas: order
    url: jdbc:mysql://localhost:3306/ddd-order?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  config: classpath:logback-local.xml
logging:
  level:
    com.example.dddorder: debug

