server:
  shutdown: graceful
  port: 8080

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ddd-order?serverTimezone=UTC&characterEncoding=UTF-8
      username: user
      password: pass
  flyway:
    user: user
    password: pass
    schemas: ddd-order
    url: jdbc:mysql://localhost:3306/ddd-order?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#logging:
#  config: classpath:logback-local.xml
logging:
  level:
    org.hibernate.SQL: debug
    com.example.dddorder: debug
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n'

