# docker-compose -p ddd-order up -d
version: "3.7"
services:
  order-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ddd-order
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql